### ISSUE TITLE
Blacklisted sites to consider adding

### ISSUE THREAD

**Issue by scottbrosnahan** [grantwinney/hide-comments-everywhere#102]
Here's my list of blacklisted sites to consider blocking by default.

undefinedbeta\.crunchyroll\.com; #place_your_selectors_here
https://beta.crunchyroll.com/
www\.youtube\.com; #place_your_selectors_here
beta\.crunchyroll\.com; #place_your_selectors_here
beta\.crunchyroll\.com; #place_your_selectors_here
https://beta.crunchyroll.com/
beta.crunchyroll.com
https://beta.crunchyroll.com/series

**Comment by grantwinney** [comment]
I assume you're talking about the reviews, like the ones listed here?
https://beta.crunchyroll.com/series/GQWH0M94E/shenmue-the-animation

Comments on the main crunchyroll.com website are already blocked, as well as on YouTube.

Let me know if you're talking about somewhere else though, or you still see comments elsewhere, and I'll take a look.

**Comment by scottbrosnahan** [comment]
the reviews under videos  and shows are still shown, anyway to hide them

**Comment by grantwinney** [comment]
@scottbrosnahan They should be hidden now. If you still see them, open the options page for the addon...

![image](https://user-images.githubusercontent.com/1354059/163819615-6125e466-951d-4c5c-a9db-c33cb587400a.png)

... and then click "Update Definitions". It should pull the latest list of sites, then try refreshing the page.

![image](https://user-images.githubusercontent.com/1354059/163819600-c4dc944f-78e1-4ea3-ba69-5380237f98ab.png)

**Comment by grantwinney** [comment]
BTW, since it looks like you were trying to add it yourself using the blacklist textbox, it would've worked if you entered it like this: (since the "reviews" section has a class attached to it named "series-reviews-section")

```
beta.crunchyroll.com; .series-reviews-section
```

**Comment by grantwinney** [comment]
I'm going to close this, but let me know if you're still having issues.
