### ISSUE TITLE
Here's a new site I'd like you to consider blocking

### ISSUE THREAD

**Issue by joshbradshaw11** [grantwinney/hide-comments-everywhere#111]
Here's a new site I'd like you to consider blocking:

www.nytimes.com

(please include any other relevant details)

**Comment by grantwinney** [comment]
Unfortunately, their content is locked behind a paywall and I don't have an account, so I can't see any comments. I tried creating a free account but that allowed me to read a single article that didn't seem to have comments anyway.

If you can provide a class name or id for the section of the page that shows the comments (you'll need to know a bit [about css selectors](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Selectors)), I'll add them to the list.

**Comment by joshbradshaw11** [comment]
Nevermind. I discovered that I can simply decline cookie access and then all comments disappear. The nytimes restyles their comments section frequently so I doubt the juice is worth the squeeze here
