### ISSUE TITLE
Instagram desktop site doesn't have blocked comments 

### ISSUE THREAD

**Issue by SlyBalto** [grantwinney/hide-comments-everywhere#113]
As far as I can tell, the add on doesn't currently block any comments on Instagram. I'd love for the site on desktop to be supported by this!!

**Comment by grantwinney** [comment]
I've tried before, but I've given up on Facebook/Instagram. The names they assign elements are very dynamic, so it's tough to block comments over the long run. A lot of other sites, like YouTube, just assign a nice ID of "comments", or at least something predictable and stable.. makes life much easier!
