### ISSUE TITLE
Blacklisted sites to consider adding

### ISSUE THREAD

**Issue by taki640** [grantwinney/hide-comments-everywhere#118]
Here's my list of blacklisted sites to consider blocking by default.

```
beta\.crunchyroll\.com; #content > div > div.app-body-wrapper > div > div > div.content-wrapper--MF5LS > div > div.commenting-wrapper
```

**Comment by grantwinney** [comment]
For some reason, it just redirects me to the main site when I go to the beta site. I added the elements you posted; let me know how it goes. Thanks.

**Comment by taki640** [comment]
Oh, you actually need an account registered in the beta to access the beta site, I completely forgot about this, sorry. But I checked and it's working fine, thank you.

**Comment by grantwinney** [comment]
Awesome, good to hear!
