### ISSUE TITLE
Blacklisted sites to consider adding

### ISSUE THREAD

**Issue by scottbrosnahan** [grantwinney/hide-comments-everywhere#119]
Here's my list of blacklisted sites to consider blocking by default.

```
(THEY'RE ON YOUR CLIPBOARD. Just paste them here and replace this line.)
```
https://beta.crunchyroll.com/
beta.crunchyroll.com
https://myanimelist.net/
https://anilist.co/

**Comment by grantwinney** [comment]
I added myanimelist.

I'm not sure which comments you'd like to block on anilist.co.. do you have an example page or two?

The beta crunchyroll site just redirects me to the non-beta site, but someone else submitted some elements to block, so maybe see if those work for you too.
