### ISSUE TITLE
Here's a new site I'd like you to consider blocking

### ISSUE THREAD

**Issue by scottbrosnahan** [grantwinney/hide-comments-everywhere#122]
Here's a new site I'd like you to consider blocking:

myanimelist.net

still has reviews showing

(please include any other relevant details)

**Comment by grantwinney** [comment]
Did you go to the options page and update the definitions?

![image](https://user-images.githubusercontent.com/1354059/185809575-ae07eca4-ad1e-4773-8dae-d50761725bab.png)

**Comment by scottbrosnahan** [comment]
updated still showing reviews

**Comment by grantwinney** [comment]
Any difference since then?
