### ISSUE TITLE
Hide featured comments on YouTube

### ISSUE THREAD

**Issue by spacecowgoesmoo** [grantwinney/hide-comments-everywhere#124]
Link: https://www.youtube.com/watch?v=sbwfpTNVFjM

![Screen Shot 2022-08-29 at 9 01 49 AM](https://user-images.githubusercontent.com/10178453/187244368-88c5d456-3956-4f4e-8e3a-05155971c914.png)

**Comment by grantwinney** [comment]
I've tried before, but I've given up on Facebook/Instagram. The names they assign elements are very dynamic, so it's tough to block comments over the long run. A lot of other sites, like YouTube, just assign a nice ID of "comments", or at least something predictable and stable.. makes life much easier!

**Comment by grantwinney** [comment]
If you update the definitions for the addon, the featured/teaser comment should be blocked now too.
