### ISSUE TITLE
Blacklisted sites to consider adding

### ISSUE THREAD

**Issue by Travelpanda** [grantwinney/hide-comments-everywhere#127]
Here's my list of blacklisted sites to consider blocking by default.

```
www.watson.ch
www.20min.ch
www.blick.ch
```

**Comment by grantwinney** [comment]
I was able to block watson.ch, update the definitions and try again.

I can't really block the other two sites. I have the same problem with Facebook. Whatever they use for their site, the class names are randomly generated, and while they _might_ stay the same for a little while, they frequently change. It makes nearly impossible to successfully block comments.

![image](https://user-images.githubusercontent.com/1354059/194723928-63f5f651-ce77-44d4-b6a7-7634925cf6dc.png)
