### ISSUE TITLE
Here's a new site I'd like you to consider blocking: facebook

### ISSUE THREAD

**Issue by iirekm** [grantwinney/hide-comments-everywhere#135]
Here's a new site I'd like you to consider blocking:

www.facebook.com

Unfortunately the plugin doesn't work with FB.

**Comment by grantwinney** [comment]
Facebook is one of a few sites that I've given up on. The names of the elements on the page are dynamic and change too often to deal with.

I don't know that it blocks comments, but you might want to check out [Fluff Busting Purity](https://chrome.google.com/webstore/detail/fluff-busting-purity/nmkinhboiljjkhaknpaeaicmdjhagpep), an extension that deals just with Facebook.
