### ISSUE TITLE
Here's a new site I'd like you to consider blocking

### ISSUE THREAD

**Issue by shane1595042264** [grantwinney/hide-comments-everywhere#154]
Here's a new site I'd like you to consider blocking:

zhuanlan.zhihu.com
https://www.zhihu.com/

Zhihu is a popular website in China. It is similar to Quora, a Q&A social media. I am not sure if it is the problem with my setup, but the comment is still there. 
![image](https://user-images.githubusercontent.com/61711097/226151614-1e8c3c36-99e3-438b-b2dd-83231c8b52a2.png)

**Comment by grantwinney** [comment]
This should be blocked now.
