### ISSUE TITLE
www.python.org - site broken in Chromium & Firefox + whitelisting broken in Firefox: need to turn off the extension

### ISSUE THREAD

**Issue by garry-ut99** [grantwinney/hide-comments-everywhere#159]
`https://www.python.org/` on both Firefox & Chromium:
- is fine with Hide Comments Everywhere disabled: [SCREENSHOOT](https://user-images.githubusercontent.com/72945564/235507989-ac3142c9-e1fe-495d-b613-4716de6c606d.png)
- is broken with Hide Comments Everywhere enabled: [SCREENSHOOT](https://user-images.githubusercontent.com/72945564/235507363-baef31fa-225c-47c7-8fca-df7c94046407.png) + message: 

> Notice: While JavaScript is not essential for this website, your interaction with the content will be limited. Please turn JavaScript on for the full experience.

Whitelisting `https://www.python.org/`:
- in Chromium (Opera) works and fixes the issue: `www\.python\.org`
- in Firefox doesn't work and creates: `undefinedwww\.python\.org`:
   - after changing to `www\.python\.org`, site still doesn't work 
   (clearing site's cookies/storage and CTRL + F5 doesn't help either)
   - need to disable the extension, and then site works again

The issues reprodued on 2 different Firefox profiles, one of them is clean - no other extensions installed.

If you run into a problem, the following information might be helpful to include, depending on what you're experiencing:

<details>
<summary>SPOILER</summary>

    Addon version: 1.6.7
    Definitions:
        Local version: 181
        Available version: 181
        Last check: Mon May 01 2023 20:17:14 GMT+0200 (czas środkowoeuropejski letni)
    Storage:
        Local: 19336 bytes
        Sync: 329 bytes
            Toggle flag settings: 24 bytes
            Personal whitelist: 55 bytes
            Personal blacklist: 210 bytes
    Environment
        User Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:109.0) Gecko/20100101 Firefox/112.0
        Platform: Win32

</details>

**Comment by grantwinney** [comment]
I think I figured out what's going on there (thanks for the details), but I'll have to wait until the addon stores publish the fix to be sure.

**Comment by grantwinney** [comment]
Thanks for all the details. Hopefully this is fixed now, in Firefox and in Chrome. Let me know if you're still having issues though.

**Comment by garry-ut99** [comment]
Confirmed fixed.
