### ISSUE TITLE
Here's a new site I'd like you to consider blocking

### ISSUE THREAD

**Issue by linzi-v7** [grantwinney/hide-comments-everywhere#162]
Here's a new site I'd like you to consider blocking:

www.hoyolab.com

It's a popular forum that discusses anime games created by the developer, Hoyoverse. It would be cool if I can only see news about the games without the comments.

Apart from comments, sometimes posts show "Hot" Comments under it [(example)](https://files.catbox.moe/r6zemg.png). If possible, please consider blocking it too.

Thanks for such a great extension!

**Comment by grantwinney** [comment]
Glad it's working out for you. :) I added the site.. after you update the definitions (on the options page), let me know if you still see comments anywhere on there.
