### ISSUE TITLE
consider blocking lwn.net comments

### ISSUE THREAD

**Issue by TheWeirdDev** [grantwinney/hide-comments-everywhere#167]
Here's a new site I'd like you to consider blocking: [lwn.net](lwn.net)

Comments take more than 90% of each page.
Looks like elements with class name `CommentBox` should to be hidden.

**Comment by grantwinney** [comment]
Thanks for looking up the selector. If you update the definitions, they should be blocked now. Let me know if I missed anything.

**Comment by TheWeirdDev** [comment]
Yes it works. Thank you.
