### ISSUE TITLE
[Feature request] Instagram post description being filtered

### ISSUE THREAD

**Issue by truenski** [grantwinney/hide-comments-everywhere#168]
A description of an Instagram post is often the main source of content for that post, and it shouldn't be filtered along with the other comments. To access certain posts on Instagram, I need to disable the extension. It would be great to have an option for this case.

**Comment by grantwinney** [comment]
I made a slight change that should catch it in one instance, but it doesn't work all the time. The problem with facebook and instagram is that the DOM on those sites is pretty random. There's not much to grab on to, to hide. On instagram, there's nothing that differentiates the OP's comment versus anyone else's.

**Comment by grantwinney** [comment]
Just adding a comment here in case someone else sees it, but I've removed Instagram. That and Facebook change too often and are difficult to block correctly and to maintain.
