### ISSUE TITLE
Sum blacklisted sites to make comments blocked by default

### ISSUE THREAD

**Issue by Watermelon2005** [grantwinney/hide-comments-everywhere#178]
gettr.com
rumble.com
banned.video.com
msn.com

these are websites to consider to being default blocked comments

**Comment by grantwinney** [comment]
Sorry it took so long to get to these. Added gettr, rumble, and msn. Not sure what banned.video.com is though. I'll close this for now, but if you want to add more comments or something and reopen it, feel free.

**Comment by Watermelon2005** [comment]
thank you so much
