### ISSUE TITLE
Extension hiding programming comments unintentionally

### ISSUE THREAD

**Issue by linzi-v7** [grantwinney/hide-comments-everywhere#179]
Hello,

I noticed the extension hides programming comments on this [site](https://java-programming.mooc.fi/part-3/1-discovering-errors) unintentionally. You can find an example of the bug under the "Commenting the Source Code" section on the page I linked.

Thanks.

**Comment by grantwinney** [comment]
I made a change to the code and google finally approved it, so once you're sure you have the latest version of the extension, see if the problem's fixed. Seems like it is...

**Comment by linzi-v7** [comment]
Looks like its fixed for me as well, thanks.
