### ISSUE TITLE
Here's a new site I'd like you to consider blocking

### ISSUE THREAD

**Issue by kosha1one** [grantwinney/hide-comments-everywhere#180]
Here's a new site I'd like you to consider blocking:

www.reddit.com

(please include any other relevant details)

Comment blocking not working on reddit, currently browsing using old reddit.

**Comment by grantwinney** [comment]
Hm, they seem to have changed some elements and they're less predictable. I'll make an update that hopefully works and doesn't break anything else.

**Comment by grantwinney** [comment]
Looks like it's working. I'll close this for now, but if you update the definitions and they're still there somewhere, just let me know.
