### ISSUE TITLE
Blacklisted sites to consider adding

### ISSUE THREAD

**Issue by Russ1409** [grantwinney/hide-comments-everywhere#181]
Here's my list of blacklisted sites to consider blocking by default.

```
undefinedwww\.youtube\.com; #place_your_selectors_here
theathletic\.com; #place_your_selectors_here```

**Comment by grantwinney** [comment]
Nothing really to go on here, but I tried adding comments for theathlethic.com. Unfortunately, I couldn't do much since they've got a paywall and I don't have an account. If you happen to know which element(s) to block, let me know.
