### ISSUE TITLE
Here's a new site I'd like you to consider blocking

### ISSUE THREAD

**Issue by Vylca** [grantwinney/hide-comments-everywhere#182]
Here's a new site I'd like you to consider blocking:

www.pinterest.fr

(please include any other relevant details)

**Comment by grantwinney** [comment]
Pinterest, much like Facebook and Instagram, is really tricky to block. They don't leave much to go on, and mostly just generate a bunch of randomly-named 3-letter class names.

I managed to hide the comments in one other area I'm seeing them, but I can only hide the comments.. not the header above them that says "3 Comments" or whatever. I'll push something out for that at least, shortly...

**Comment by grantwinney** [comment]
I updated pinterest.com and added pinterest.fr and it looks okay. Hides all the comment, if not quite all the related elements in the comments section. I think that's the best I can do though. Let me know if you still see them anywhere.
