### ISSUE TITLE
Here's a new site I'd like you to consider blocking

### ISSUE THREAD

**Issue by honeylemontea** [grantwinney/hide-comments-everywhere#184]
Here's a new site I'd like you to consider blocking:

magusmanga.com

(please include any other relevant details)

**Comment by grantwinney** [comment]
It looks like they're just using disqus and that's already blocked. Do you have a particular page where comments are still showing?

**Comment by honeylemontea** [comment]
> It looks like they're just using disqus and that's already blocked. Do you have a particular page where comments are still showing?

Oh, thanks for the heads up. Never mind me then, closing thread
