### ISSUE TITLE
Need to fix for www.reddit.com

### ISSUE THREAD

**Issue by iJustErikk** [grantwinney/hide-comments-everywhere#185]
This extension no longer works at www.reddit.com. Seems like we could just target #comment-tree-content-anchor-XXXXX not sure if we do exact matches or if we can figure in prefixes as well. 

Do we? If we don't, would anyone have any input if I were to implement these to work with prefixes?

Since we run into external compatibility issues, we could run weekly puppeteer + this extension tests and some links we know have comments (for public access platforms). Though, these tests may run into external compatibility if the website changes.

**Comment by grantwinney** [comment]
@iJustErikk I'm not having a problem with reddit (using edge on a laptop), but maybe it depends on the page or the view. Can you let me know of a thread that you're seeing comments on? Also, your browser and whether you're on mobile may help. Who knows how they might switch up the DOM depending on how you're using the site...

If there's an id that ends up being a more reliable match, even if the end of it changes, it's certainly doable. I've got other stuff in the [sites.json](https://github.com/grantwinney/hide-comments-everywhere/blob/master/sites/sites.json) file like that.

```css
div[id^='comment-tree-content-anchor']
```

**Comment by grantwinney** [comment]
Now I see it. Okay, I've applied a fix. Try updating the definitions on the options page and see if it works better.
