### ISSUE TITLE
Here's a new site I'd like you to consider blocking

### ISSUE THREAD

**Issue by 2marvin2** [grantwinney/hide-comments-everywhere#186]
Here's a new site I'd like you to consider blocking:

www.backloggd.com

(please include any other relevant details)

**Comment by grantwinney** [comment]
Do you want to block the reviews? That seems like a major function of this particular site, at least from what I can see without creating an account. Or are there a lot of other features, and the reviews go off the rails sometimes?

**Comment by grantwinney** [comment]
Closing for now.
