### ISSUE TITLE
only blocks the first loaded posts in facebook

### ISSUE THREAD

**Issue by AlizerUncaged** [grantwinney/hide-comments-everywhere#188]
any subsequent posts loaded dynamically will still show the comments

**Comment by grantwinney** [comment]
Unfortunately, Facebook is about the only site [I've given up on](https://github.com/grantwinney/hide-comments-everywhere/wiki/Why-isn't-Facebook-blocked%3F). I'm surprised this addon works on FB at all. Their DOM is just too random to consistently block.
