### ISSUE TITLE
i want to allow  specific utube channels comments

### ISSUE THREAD

**Issue by plautus2** [grantwinney/hide-comments-everywhere#191]
I want to block all comments but whitelist a couple youtube channels that I follow. So basically I only want to communicate wiht the author. 
can u make this work?

**Comment by grantwinney** [comment]
Sorry, that's not something I've got the time to do with this extension, tailoring it so heavily for YouTube. It would take a lot of extra code to make it work, if it's possible at all. Somehow I'd have to scrape the user or channel name off the page to see if it should be blocked, or maybe call some YouTube API or something.

In theory the custom whitelist on the options screen might help, if only the URL of a video contained the author's name or their channel name. But once you're viewing a video, the URL just starts with "https://www.youtube.com/watch?v=", so there's no easy way to whitelist them, unfortunately.
