### ISSUE TITLE
Here's a new site I'd like you to consider blocking

### ISSUE THREAD

**Issue by TheWeirdDev** [grantwinney/hide-comments-everywhere#194]
Here's a new site I'd like you to consider blocking:

cohost.org

The css selector for comments is `.co-comment-box`

**Comment by grantwinney** [comment]
Thanks for adding the selector.. makes life easier. :)

I added a couple other ones to block some other comment-related elements. After you update the definition you should see the changes.

**Comment by TheWeirdDev** [comment]
Awesome!
