### ISSUE TITLE
Here's a new site I'd like you to consider blocking

### ISSUE THREAD

**Issue by dogukansahil** [grantwinney/hide-comments-everywhere#199]
Here's a new site I'd like you to consider blocking:

twitter.com

(please include any other relevant details)

**Comment by klaire1997** [comment]
yeah, the extension fails to work on twitter yet again. thanks elon!

**Comment by grantwinney** [comment]
Kept putting this off because I figured it'd be a pain to figure out what they changed, but it's just due to the domain change. That doesn't happen often.. 🙄

**Comment by klaire1997** [comment]
> Kept putting this off because I figured it'd be a pain to figure out what they changed, but it's just due to the domain change. That doesn't happen often.. 🙄

you're doing god's work, thank you.
