### ISSUE TITLE
Blacklisted sites to consider adding

### ISSUE THREAD

**Issue by drekzikko** [grantwinney/hide-comments-everywhere#206]
Here's my list of blacklisted sites to consider blocking by default.

```
www\.instagram\.com; .x5yr21d  > .x78zum5.xdt5ytf.x1iyjqo2

**Comment by grantwinney** [comment]
Thanks for figuring out the exact elements. Hopefully it works for awhile.. I haven't had too much luck in the past. Sorry for the long delay!
