### ISSUE TITLE
Here's a new site I'd like you to consider blocking

### ISSUE THREAD

**Issue by maxgohren** [grantwinney/hide-comments-everywhere#207]
Here's a new site I'd like you to consider blocking:

www.instagram.com

Content appears in left of frame with comments rectangle on the right, would be absolutely lovely to remove this comment box, seems to be an easily contained element in the page!

Great project thanks so much!

**Comment by grantwinney** [comment]
Sorry for such a long delay in responding! I made a change that hopefully will fix instagram for now. The names of elements are random and change often, which make it tough to pin down.
