### ISSUE TITLE
Blacklisted sites to consider adding

### ISSUE THREAD

**Issue by Deannolan777** [grantwinney/hide-comments-everywhere#222]
Here's my list of blacklisted sites to consider blocking by default.

```
undefinedwww\.instagram\.com; #place_your_selectors_here
https://www.instagram.com/
```

**Comment by grantwinney** [comment]
I've tried, but Instagram (and Facebook) are too time-consuming to reliably block.

https://github.com/grantwinney/hide-comments-everywhere/wiki/Why-isn't-Facebook-blocked
