### ISSUE TITLE
Extension for Microsoft Edge

### ISSUE THREAD

**Issue by Bishyandreadytodie** [grantwinney/hide-comments-everywhere#224]
Is it possible to make this extension available for Microsoft Edge, or is it difficult to do that?

**Comment by grantwinney** [comment]
I use Edge daily and it works fine.. just go to the Chrome addons page and Edge will let you add extensions directly from there. If you mean adding it to the Edge Addons store, I'd rather not have to upload updates to this to multiple places.

**Comment by Bishyandreadytodie** [comment]
Oh thank you so much, that works.
