### ISSUE TITLE
Twitter's new "Explore" section in the homepage

### ISSUE THREAD

**Issue by linzi-v7** [grantwinney/hide-comments-everywhere#225]
Twitter recently added a new "Explore" Beta section to their site which seems to make AI titles on trending topics (example given in the attached image), it has been a bit annoying scrolling through the homepage with it there but I thankfully got it blocked for now. I added the selector for the section that worked for me.
![image](https://github.com/user-attachments/assets/37ce6647-85e9-4af5-9fa6-74aa730d3755)

blocklist:
```
x.com; div[aria-label="Timeline: Trending now"]

```

**Comment by grantwinney** [comment]
Hi @linzi-v7, I used to have a separate addon just for hiding elements on Twitter, but it's not in the store anymore. This section you're talking about looks annoying for sure, but if it's not comments, then I don't want to block it using this addon.

I haven't used it, but [SocialFocus](https://chromewebstore.google.com/detail/socialfocus-hide-distract/abocjojdmemdpiffeadpdnicnlhcndcg) looks promising. [Simplified Twitter](https://chromewebstore.google.com/detail/simplified-twitter/kfopmjhmejbgomgeajemgpgpbckpoopg) looks good too, although the informational block at the top of that one indicates they haven't upgraded to MV3 (not a big deal, but Google's been pushing it), so it might disappear from the store.
