### ISSUE TITLE
Blacklisted sites to consider adding

### ISSUE THREAD

**Issue by SteveMarkovits** [grantwinney/hide-comments-everywhere#227]
Here's my list of blacklisted sites to consider blocking by default.

```
https://www.nintendolife.com/
https://www.theguardian.com/
https://www.pushsquare.com/
```

**Comment by grantwinney** [comment]
I checked all three of these out, and comments are blocked on all of them. Do you have any example pages I could check out?

**Comment by grantwinney** [comment]
Closing this for now, but let me know if you have more details.
