### ISSUE TITLE
Here's a new site I'd like you to consider blocking

### ISSUE THREAD

**Issue by ladj2703** [grantwinney/hide-comments-everywhere#229]
Here's a new site I'd like you to consider blocking:

bsky.app

(please include any other relevant details)

**Comment by ladj2703** [comment]
I tried adding it to the custom blacklist, to no avail.

**Comment by grantwinney** [comment]
It's kinda all comments, like x, but I tried blocking replies. Let me know how it goes.

**Comment by ladj2703** [comment]
Hello, 
Yes, I noticed it's completely different now. 
Before the changes you made, the extension had no effect on BlueSky. Now, it has the desired behaviour, essentially the same as on X. 
Regards!

**Comment by grantwinney** [comment]
Awesome, thanks for letting me know.
