### ISSUE TITLE
Comments not blocked for sporting events on Google

### ISSUE THREAD

**Issue by OJ7** [grantwinney/hide-comments-everywhere#31]
Example Link:
https://www.google.com/search?q=epl&oq=epl&aqs=chrome..69i57j0l5.827j0j7&sourceid=chrome&ie=UTF-8#sie=m;/g/11f67fmb1q;2;/m/02_tc;lco;fp;1;;

**Comment by grantwinney** [comment]
They don't have many identifiers and stuff to hook onto, but I think I managed it. If you don't go directly to the comments page, the "Comments" tab should be gone now.

https://www.google.com/search?newwindow=1&source=hp&ei=RKHQXLe4Loby5gKJgYX4Bg&q=newcastle+vs+liverpool&oq=newcastle+vs+&gs_l=psy-ab.1.0.0i131j0j0i3j0l7.450.1903..2709...0.0..0.113.1112.13j1......0....1..gws-wiz.....0..0i10.b-EnJOWnjyo#sie=m;/g/11f67fmb1q;2;/m/02_tc;dt;fp;1;;

**Comment by OJ7** [comment]
Seems to be a little better now. The "Comments" tab still shows up but it goes away after clicking on it (but still loads comments).

**Comment by grantwinney** [comment]
When I search for newcastle vs liverpool and click the result, I don't see the comments tab at all, so I can't choose to view the comments. Do you have a different link?

![2019-05-06 20_27_44-newcastle vs liverpool](https://user-images.githubusercontent.com/1354059/57263111-7cc34a00-703d-11e9-9f57-900ac34224a9.png)

**Comment by OJ7** [comment]
You can search "epl" and it should look something like this:

![image](https://user-images.githubusercontent.com/5333243/57314964-9fe30d80-70c0-11e9-9ee6-02e4593565da.png)

Clicking on any match shows the "Comments" tab:

![image](https://user-images.githubusercontent.com/5333243/57315001-affaed00-70c0-11e9-97e2-5889cd7a58d6.png)


Clicking on the "Comments" tab makes it disappear but the comments still show:

![image](https://user-images.githubusercontent.com/5333243/57315041-c43eea00-70c0-11e9-99b1-b3d7f9905937.png)

Changing to another tab hides the comments and they are no longer accessible. 
Also refreshing the page while viewing one of the matches hides the "Comments" tab right away sometimes.

**Comment by grantwinney** [comment]
Wow, I forgot this was open. I recently rewrote the whole extension to do what it does differently, but I'm still unable to find a good way to hide comments if someone opens a link that takes them _directly_ to the comments page. For now, I'm just going to settle for hiding the "Comments" link.

I doubt this is still a concern for you after all this time, but if it is feel free to reach out. 😅
