### ISSUE TITLE
Support for Firefox

### ISSUE THREAD

**Issue by Abhishek-dev2** [grantwinney/hide-comments-everywhere#32]
Readme of the extensions mentions that this extension works for Firefox too, but I cannot find the extension in Firefox add-ons. How do I enable the extension in Firefox?

Btw, thanks for one of the best extensions of all time.

**Comment by grantwinney** [comment]
Thanks @Abhishek-dev2 glad you like it!

I don't use Firefox much.. I know I had it in their store at one time but then I disabled it. I guess I just forgot about it. It _should_ work just fine... I updated and re-enabled it.

https://addons.mozilla.org/en-US/firefox/addon/hide-comments-everywhere/

Let me know how it goes! :)

**Comment by Abhishek-dev2** [comment]
Thank you very much.
