### ISSUE TITLE
Here's a new site I'd like you to consider blocking

### ISSUE THREAD

**Issue by skbjones** [grantwinney/hide-comments-everywhere#39]
Here's a new site I'd like you to consider blocking:

https://www.pinterest.com/pin/636344622347441459/

(please include any other relevant details)

**Comment by grantwinney** [comment]
Comments should be blocked now.. you can update the definitions on the options page. Let me know if you still see them somewhere on there.

**Comment by grantwinney** [comment]
Let me know if you run into more issues.
