### ISSUE TITLE
Here's a new site I'd like you to consider blocking

### ISSUE THREAD

**Issue by lianlianyee** [grantwinney/hide-comments-everywhere#41]
https://www.facebook.com/natalie.c.wt.3
https://www.facebook.com/yceugenia.gohii.3 
https://www.facebook.com/Eugenia.Gyc
https://www.facebook.com/esthercfy
https://www.facebook.com/Decofone/
([Here's]
https://www.facebook.com/DLadiesWardrobe/
)))))) a new site I'd like you to consider blocking:

https://www.facebook.com/dkiddowardrobe0914/

(please include any other relevant details)

**Comment by grantwinney** [comment]
Facebook's a royal pain to try blocking comments on. It's unpredictable where they load comments from one page to another. I've tried several times. I'll take a look at this again, but it'll have to wait a bit until I've got more time.

**Comment by grantwinney** [comment]
I've tried quite a bit, and nothing ever sticks. I'd suggest looking for an extension that specifically addresses facebook, or a style to use with the "stylus" extension.
