### ISSUE TITLE
Here's a new site I'd like you to consider blocking

### ISSUE THREAD

**Issue by o-fernandez** [grantwinney/hide-comments-everywhere#45]
Here's a new site I'd like you to consider blocking:

https://www.houzz.com

There's a comments div in articles like this: <div scopeid="comments-content" class="hz-editorial-gallery__left__section hz-editorial-gallery__section--comments">

Example: https://www.houzz.com/magazine/7-ways-to-get-your-container-garden-ready-for-winter-stsetivw-vs~113763591

(please include any other relevant details)

**Comment by grantwinney** [comment]
If you update the definitions, it should be good now.

**Comment by zaba-monika** [comment]
You guys serious?  Why spam the repository with threads with the same useless title over and over again? 
It would be much more useful if you guys were to create threads like "add yoursite.com"

**Comment by grantwinney** [comment]
@zaba-monika It's because they're using functionality built into the browser addon, which takes them to this issues page, and fills in the title and body for them.

**Comment by zaba-monika** [comment]
Oh well, I see now...but:
- it does not change what I've just said, they still can and should change it
- also a question to You, why not just made it simpler and shorten to "Add <website>" ? ...
