### ISSUE TITLE
o2.pl - bad hiding: comments not hidden, some images hidden instead

### ISSUE THREAD

**Issue by zaba-monika** [grantwinney/hide-comments-everywhere#46]
My browser Firefox 83

Example link to article with the issue:
https://www.o2.pl/informacje/chwalila-sie-na-instagramie-swoim-bogactwem-gwiazde-spotkalo-cos-strasznego-6580881803643840a

The issue (expand spoilers to see screenshoots): 

<details not-open>
<summary>comments aren't hidden::</summary>

![capture_157_29-11-2020_18-46-11](https://user-images.githubusercontent.com/72980128/100549425-306cda00-3273-11eb-9869-18de111fe077.png)
![capture_158_29-11-2020_18-46-14](https://user-images.githubusercontent.com/72980128/100549426-31057080-3273-11eb-8230-0b13d79a65c7.png)
![capture_159_29-11-2020_18-46-18](https://user-images.githubusercontent.com/72980128/100549428-31057080-3273-11eb-9cc7-396c0247aad3.png)

</details>

<details not-open>
<summary>instead, it hides some images above the comments:</summary>

![capture_155_29-11-2020_18-46-05](https://user-images.githubusercontent.com/72980128/100549454-54302000-3273-11eb-979c-b225cad6fce5.png)
![capture_156_29-11-2020_18-46-07](https://user-images.githubusercontent.com/72980128/100549455-55614d00-3273-11eb-9c55-5fe192f11e55.png)
</details>

<details not-open>
<summary>the images are back after disabling the extension on o2.pl, using "Toggle comments" button:</summary>

![capture_160_29-11-2020_18-50-21](https://user-images.githubusercontent.com/72980128/100549545-d3255880-3273-11eb-982e-1258106436fc.png)
![capture_161_29-11-2020_18-50-27](https://user-images.githubusercontent.com/72980128/100549546-d3bdef00-3273-11eb-9554-73ad1da543d4.png)

</details>

Btw good extension.
It excellently hides all these stupid trollish comments which litter the entire internet.
I have it enabled all the time, and only sometimes disable on particular sites to read comments if I'm interested.
Life is much better with this addon!

**Comment by grantwinney** [comment]
Thanks for the kind words, glad you find it useful! I use it too. It could use some improvements, but I'm glad it works pretty well as-is.

I'll check into your issue when I get a chance here - thanks for the extra details.

---

_About your comment on the other issues, it sounded friendlier I guess? I didn't give the title a lot of thought. It doesn't bug me either way, and I doubt anyone else sees them unless they go looking for them._

**Comment by grantwinney** [comment]
Whew, time flies. I finally got around to looking at this. The DOM elements on that site are pretty randomly named, but hopefully it's fixed.
