### ISSUE TITLE
Here's a new site I'd like you to consider blocking

### ISSUE THREAD

**Issue by Pleytos** [grantwinney/hide-comments-everywhere#50]
Here's a new site I'd like you to consider blocking. (include as many details as possible)
https://tweakers.net
For example:
https://tweakers.net/nieuws/176968/tele2-klanten-melden-verbindingsproblemen-na-overstap-op-netwerk-t-mobile.html

I don't know what details I should include. I will try to answer any question that pops up.

**Comment by grantwinney** [comment]
Let me know if I missed anything and I'll reopen this...
