### ISSUE TITLE
Here's a new site I'd like you to consider blocking

### ISSUE THREAD

**Issue by timofey71** [grantwinney/hide-comments-everywhere#67]
Here's a new site I'd like you to consider blocking:

https://vk.com

(please include any other relevant details)

**Comment by grantwinney** [comment]
I don't have an account with them so I can't see much. I already block some comments on their site. Is there a specific page you're seeing comments on?

**Comment by timofey71** [comment]
Hello,

Yes, the usual comments on VK are blocked with your extension. But if someone shares a post with me, its comments are visible:



They’re in a layer named #pv_comments. Hiding the layer hides comments.

**Comment by grantwinney** [comment]
Sorry it took so long to revisit this! I added that element in there, `#pv_comments`, but like I said I can't confirm that it's working. I'll close this for now, but let me know if it's still not and you figure out the correct element to hide, and I'll adjust it.

**Comment by timofey71** [comment]
Hello and thank you, I’ll test it. Best regards,Timofey Sherudilohttps://timofey-sherudilo.ru From: GrantSent: 28 сентября 2021 г. 23:58To: grantwinney/hide-comments-everywhereCc: timofey71; AuthorSubject: Re: [grantwinney/hide-comments-everywhere] Here's a new site I'd like you to consider blocking (#67) Sorry it took so long to revisit this! I added that element in there, #pv_comments, but like I said I can't confirm that it's working. I'll close this for now, but let me know if it's still not and you figure out the correct element to hide, and I'll adjust it.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
