### ISSUE TITLE
Extension not working properly in Kiwi Browser

### ISSUE THREAD

**Issue by bdknguyen** [grantwinney/hide-comments-everywhere#69]
Hi,
I'm using this extension on Kiwi Browser for Android, and it doesn't immediately block comments when I visit a website. Instead, I have to press the button to toggle comments twice before the comments disappear. Could you please look into this? Thanks!

**Comment by grantwinney** [comment]
I'm not familiar with the kiwi browser, and haven't tested it on mobile at all. I published a new version recently that cleaned things up and fixed a few bugs.. hopefully it fixed the issue you were experiencing too.
