### ISSUE TITLE
Here's a new site I'd like you to consider blocking

### ISSUE THREAD

**Issue by RachelwasHere** [grantwinney/hide-comments-everywhere#70]
Here's a new site I'd like you to consider blocking:

https://theathletic.com

(please include any other relevant details)

**Comment by grantwinney** [comment]
Hm, since the site's behind a paywall, I can't really get to the comments section.

I'm going to close this for now, but if you're able to figure out which part of the html contains the comments, and you want to paste it here, I'll try figuring it out from that.
