### ISSUE TITLE
Slight delay with new Reddit Layout

### ISSUE THREAD

**Issue by digitalblossom** [grantwinney/hide-comments-everywhere#78]
With the new Reddit layout, there is a 1 to 2 second delay before the comment section disappears, during which comments are visible.

Brave Version 1.31.87 (Chromium: 95.0.4638.54)
Extension VER 1.4.3 (129)

**Comment by grantwinney** [comment]
I put out a new version (1.5.1). Does it work any faster with reddit?

**Comment by grantwinney** [comment]
Closing. Let me know if you have any other issues.
