### ISSUE TITLE
Feature request: enable YouTube channel-specific (or even video-specific) comments section blocking

### ISSUE THREAD

**Issue by GalGreenfield** [grantwinney/hide-comments-everywhere#79]
Continuing with on with the goal of the this project:
> Fed up with the vitriol left in comments, many sites are dumping their comment systems completely. It's just too costly to monitor them, so they tend to devolve into a cess pool. Personally, I just want the content most of the time. YouTube anyone?
> 
> To help with my own sanity (and maybe yours?), I wrote an extension that hides many comment systems - identifying them is somewhat predictable. It's available for Chrome and Firefox, or you can read more about it here too.

I suggest adding channel-specific blocking of comments, to not block out all channels' comments section, sometimes a person might want to see coments of a specific channel - or participate in them. In my case, for example, I'm subscribed to various technology reviewing channels. One of which promotes positivity and is also a small community. Unlike most of the ones whose contents I like to consume, but dislike their comments section, in this one I sometimes like to read the comments. Another reason to have the ability to make it channel-specific: write coments in channels you want to be able to comment on videos of.

I think it would be even better to have the ability to toggle for a specific video. That would be useful for various situations, for example a disucssion of contents of a video you're interested in discussioning (and don't care about commenting on other videos - even if they're from the same channel), and in competitions and challenges presented in videos answered are asked for (e.g educational videos). I personally am subscribed to channels who've made **various** videos of **both** of the scenarios I mentioned.

**Comment by grantwinney** [comment]
That's a great idea, but it goes beyond what I want to do with this extension. It'd involve a lot of customization for just a single site, and I'm not even sure how someone would tackle it, since the URLs for videos have nothing connecting them to a specific channel. I think someone would need to write a separate addon that uses the [YouTube API](https://developers.google.com/youtube/v3/docs/search/list).

**Comment by grantwinney** [comment]
Closing this out. I do think it's a nice idea, but it's just not feasible for this addon.
