### ISSUE TITLE
A simple thank you

### ISSUE THREAD

**Issue by MrChocolatine** [grantwinney/hide-comments-everywhere#85]
Not an issue, nothing much to say, but a thank you for your extension.

I have been using it for months now, and I thought it would be pleasant to at least thank the author.

For years now comments section tend to be the worst place and it is easy to get triggered for nothing, while you just want to enjoy a content. Your extension saves lives! (okay I am joking but at least it brings inner peace, that is true)

Keep up the good work!

**Comment by grantwinney** [comment]
Thanks for reaching out!! Glad to hear it's doing its job, and helping more people than just me. 😄
