### ISSUE TITLE
https://beta.crunchyroll.com/watch/G6JK7W70R/girl-of-steel

### ISSUE THREAD

**Issue by arch1x** [grantwinney/hide-comments-everywhere#94]
Here's a new site I'd like you to consider blocking:

https://beta.crunchyroll.com

(please include any other relevant details)

**Comment by grantwinney** [comment]
Comments on crunchyroll.com are already blocked. I don't have an account so I can't see anything on beta.crunchyroll.com, but if comments are still showing up on there, I'll need to be able to see the page source code. You could either post it here or somewhere else like pastebin and then post a link, and I'll try to figure it out.
