### ISSUE TITLE
Warning in console [DevTools failed to load source map: Could not load content for...]

### ISSUE THREAD

**Issue by stephanedemotte** [grantwinney/hide-comments-everywhere#99]
<img width="511" alt="Screen Shot 2022-03-19 at 7 42 03 AM" src="https://user-images.githubusercontent.com/2158130/159119697-2e0bef21-960f-41d0-ba03-133df546912e.png">

Thank you !

**Comment by grantwinney** [comment]
Where are you seeing this? On a particular site or all of them? Which browser? Any other details you can share would help.

**Comment by grantwinney** [comment]
Let me know if you have any other details and I'll look into this. I'm not seeing the error in my browser.
